package edu.bridgeport.cpsc350.project1.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import edu.bridgeport.cpsc350.project1.model.Account;
import edu.bridgeport.cpsc350.project1.model.AccountExample;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    int countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    int deleteByPrimaryKey(Integer accountno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    Account selectByPrimaryKey(Integer accountno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    int updateByPrimaryKey(Account record);
}