package edu.bridgeport.cpsc350.project1.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import edu.bridgeport.cpsc350.project1.model.Customer;
import edu.bridgeport.cpsc350.project1.model.CustomerExample;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    int countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    int deleteByPrimaryKey(Integer custid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
	Customer selectByPrimaryKey(Integer custid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    int updateByPrimaryKey(Customer record);
}