package edu.bridgeport.cpsc350.project1.dao;

import edu.bridgeport.cpsc350.project1.model.Trade;
import edu.bridgeport.cpsc350.project1.model.TradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE_VIEW
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    int countByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE_VIEW
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    int deleteByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE_VIEW
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    int insert(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE_VIEW
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    int insertSelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE_VIEW
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    List<Trade> selectByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE_VIEW
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    int updateByExampleSelective(@Param("record") Trade record, @Param("example") TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRADE_VIEW
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    int updateByExample(@Param("record") Trade record, @Param("example") TradeExample example);
}