package edu.bridgeport.cpsc350.project1.model;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.ACCOUNTNO
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    private Integer accountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.OPENDATE
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    private String opendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.ACCOUNTTYPE
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    private String accounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.ACCOUNTSTATE
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    private String accountstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.BALANCE
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.CUSTID
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    private Integer custid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT.BANKID
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    private Integer bankid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ACCOUNTNO
     *
     * @return the value of ACCOUNT.ACCOUNTNO
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public Integer getAccountno() {
        return accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ACCOUNTNO
     *
     * @param accountno the value for ACCOUNT.ACCOUNTNO
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public void setAccountno(Integer accountno) {
        this.accountno = accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.OPENDATE
     *
     * @return the value of ACCOUNT.OPENDATE
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public String getOpendate() {
        return opendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.OPENDATE
     *
     * @param opendate the value for ACCOUNT.OPENDATE
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public void setOpendate(String opendate) {
        this.opendate = opendate == null ? null : opendate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ACCOUNTTYPE
     *
     * @return the value of ACCOUNT.ACCOUNTTYPE
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public String getAccounttype() {
        return accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ACCOUNTTYPE
     *
     * @param accounttype the value for ACCOUNT.ACCOUNTTYPE
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public void setAccounttype(String accounttype) {
        this.accounttype = accounttype == null ? null : accounttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.ACCOUNTSTATE
     *
     * @return the value of ACCOUNT.ACCOUNTSTATE
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public String getAccountstate() {
        return accountstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.ACCOUNTSTATE
     *
     * @param accountstate the value for ACCOUNT.ACCOUNTSTATE
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public void setAccountstate(String accountstate) {
        this.accountstate = accountstate == null ? null : accountstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.BALANCE
     *
     * @return the value of ACCOUNT.BALANCE
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.BALANCE
     *
     * @param balance the value for ACCOUNT.BALANCE
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.CUSTID
     *
     * @return the value of ACCOUNT.CUSTID
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public Integer getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.CUSTID
     *
     * @param custid the value for ACCOUNT.CUSTID
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public void setCustid(Integer custid) {
        this.custid = custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT.BANKID
     *
     * @return the value of ACCOUNT.BANKID
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public Integer getBankid() {
        return bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT.BANKID
     *
     * @param bankid the value for ACCOUNT.BANKID
     *
     * @mbggenerated Sat Oct 31 14:04:36 EDT 2015
     */
    public void setBankid(Integer bankid) {
        this.bankid = bankid;
    }
}