package edu.bridgeport.cpsc350.project1.model;

public class Card {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDITCARD.CARDID
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    private Integer cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDITCARD.CARDNO
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDITCARD.OPENDATE
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    private String opendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDITCARD.EXPIREDATE
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    private String expiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDITCARD.CVV
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    private String cvv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDITCARD.PASSWORD
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDITCARD.CARDTYPE
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    private String cardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDITCARD.CARDSTATUS
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    private String cardstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDITCARD.ACCOUNTNO
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    private Integer accountno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDITCARD.CARDID
     *
     * @return the value of CREDITCARD.CARDID
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public Integer getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDITCARD.CARDID
     *
     * @param cardid the value for CREDITCARD.CARDID
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public void setCardid(Integer cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDITCARD.CARDNO
     *
     * @return the value of CREDITCARD.CARDNO
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDITCARD.CARDNO
     *
     * @param cardno the value for CREDITCARD.CARDNO
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDITCARD.OPENDATE
     *
     * @return the value of CREDITCARD.OPENDATE
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public String getOpendate() {
        return opendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDITCARD.OPENDATE
     *
     * @param opendate the value for CREDITCARD.OPENDATE
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public void setOpendate(String opendate) {
        this.opendate = opendate == null ? null : opendate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDITCARD.EXPIREDATE
     *
     * @return the value of CREDITCARD.EXPIREDATE
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public String getExpiredate() {
        return expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDITCARD.EXPIREDATE
     *
     * @param expiredate the value for CREDITCARD.EXPIREDATE
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public void setExpiredate(String expiredate) {
        this.expiredate = expiredate == null ? null : expiredate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDITCARD.CVV
     *
     * @return the value of CREDITCARD.CVV
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public String getCvv() {
        return cvv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDITCARD.CVV
     *
     * @param cvv the value for CREDITCARD.CVV
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public void setCvv(String cvv) {
        this.cvv = cvv == null ? null : cvv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDITCARD.PASSWORD
     *
     * @return the value of CREDITCARD.PASSWORD
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDITCARD.PASSWORD
     *
     * @param password the value for CREDITCARD.PASSWORD
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDITCARD.CARDTYPE
     *
     * @return the value of CREDITCARD.CARDTYPE
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public String getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDITCARD.CARDTYPE
     *
     * @param cardtype the value for CREDITCARD.CARDTYPE
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype == null ? null : cardtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDITCARD.CARDSTATUS
     *
     * @return the value of CREDITCARD.CARDSTATUS
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public String getCardstatus() {
        return cardstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDITCARD.CARDSTATUS
     *
     * @param cardstatus the value for CREDITCARD.CARDSTATUS
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public void setCardstatus(String cardstatus) {
        this.cardstatus = cardstatus == null ? null : cardstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDITCARD.ACCOUNTNO
     *
     * @return the value of CREDITCARD.ACCOUNTNO
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public Integer getAccountno() {
        return accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDITCARD.ACCOUNTNO
     *
     * @param accountno the value for CREDITCARD.ACCOUNTNO
     *
     * @mbggenerated Sat Oct 31 22:10:08 EDT 2015
     */
    public void setAccountno(Integer accountno) {
        this.accountno = accountno;
    }
}