package edu.bridgeport.cpsc350.project1.model;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUSTID
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    private Integer custid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUSTNAME
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.IDENTITYPE
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    private String identitype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.IDENTITYID
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    private String identityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.BIRTHDAY
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.STREET
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CITY
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.STATE
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.GENDER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.EDUCATION
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    private String education;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUSTID
     *
     * @return the value of CUSTOMER.CUSTID
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public Integer getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUSTID
     *
     * @param custid the value for CUSTOMER.CUSTID
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public void setCustid(Integer custid) {
        this.custid = custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUSTNAME
     *
     * @return the value of CUSTOMER.CUSTNAME
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUSTNAME
     *
     * @param custname the value for CUSTOMER.CUSTNAME
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.IDENTITYPE
     *
     * @return the value of CUSTOMER.IDENTITYPE
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public String getIdentitype() {
        return identitype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.IDENTITYPE
     *
     * @param identitype the value for CUSTOMER.IDENTITYPE
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public void setIdentitype(String identitype) {
        this.identitype = identitype == null ? null : identitype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.IDENTITYID
     *
     * @return the value of CUSTOMER.IDENTITYID
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public String getIdentityid() {
        return identityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.IDENTITYID
     *
     * @param identityid the value for CUSTOMER.IDENTITYID
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public void setIdentityid(String identityid) {
        this.identityid = identityid == null ? null : identityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.BIRTHDAY
     *
     * @return the value of CUSTOMER.BIRTHDAY
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.BIRTHDAY
     *
     * @param birthday the value for CUSTOMER.BIRTHDAY
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.STREET
     *
     * @return the value of CUSTOMER.STREET
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.STREET
     *
     * @param street the value for CUSTOMER.STREET
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CITY
     *
     * @return the value of CUSTOMER.CITY
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CITY
     *
     * @param city the value for CUSTOMER.CITY
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.STATE
     *
     * @return the value of CUSTOMER.STATE
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.STATE
     *
     * @param state the value for CUSTOMER.STATE
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.GENDER
     *
     * @return the value of CUSTOMER.GENDER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.GENDER
     *
     * @param gender the value for CUSTOMER.GENDER
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.EDUCATION
     *
     * @return the value of CUSTOMER.EDUCATION
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.EDUCATION
     *
     * @param education the value for CUSTOMER.EDUCATION
     *
     * @mbggenerated Sat Oct 31 23:06:38 EDT 2015
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }
}