package edu.bridgeport.cpsc350.project1.model;

public class Trade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.TRADEID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private Integer tradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.TADETIME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String tadetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.AMOUNT
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.CARDID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private Integer cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.TRADETYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String tradetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.TRADETYPENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String tradetypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.CARDNO
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.COPENDATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String copendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.EXPIREDATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String expiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.CARDTYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String cardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.CARDTYPENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String cardtypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.CARDSTATUS
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String cardstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.CARDSTATUSNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String cardstatusname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.MERCHANTID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private Integer merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.MERCHANTNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String merchantname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.MERCHANTTYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String merchanttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.MERCHANTTYPENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String merchanttypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.ACCOUNTNO
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private Integer accountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.AOPENDATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String aopendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.ACCOUNTTYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String accounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.ACCOUNTTYPENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String accounttypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.ACCOUNTSTATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String accountstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.ACCOUNTSTATUSNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String accountstatusname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.BALANCE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.CUSTID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private Integer custid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.CUSTNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.IDENTITYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String identitype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.IDENTITYID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String identityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.BIRTHDAY
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.STREET
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.CITY
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.CITYNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.STATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.STATENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String statename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.GENDER
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.GENDERNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String gendername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.EDUCATION
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADE_VIEW.EDUNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    private String eduname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.TRADEID
     *
     * @return the value of TRADE_VIEW.TRADEID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public Integer getTradeid() {
        return tradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.TRADEID
     *
     * @param tradeid the value for TRADE_VIEW.TRADEID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setTradeid(Integer tradeid) {
        this.tradeid = tradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.TADETIME
     *
     * @return the value of TRADE_VIEW.TADETIME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getTadetime() {
        return tadetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.TADETIME
     *
     * @param tadetime the value for TRADE_VIEW.TADETIME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setTadetime(String tadetime) {
        this.tadetime = tadetime == null ? null : tadetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.AMOUNT
     *
     * @return the value of TRADE_VIEW.AMOUNT
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.AMOUNT
     *
     * @param amount the value for TRADE_VIEW.AMOUNT
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.CARDID
     *
     * @return the value of TRADE_VIEW.CARDID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public Integer getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.CARDID
     *
     * @param cardid the value for TRADE_VIEW.CARDID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setCardid(Integer cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.TRADETYPE
     *
     * @return the value of TRADE_VIEW.TRADETYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getTradetype() {
        return tradetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.TRADETYPE
     *
     * @param tradetype the value for TRADE_VIEW.TRADETYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setTradetype(String tradetype) {
        this.tradetype = tradetype == null ? null : tradetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.TRADETYPENAME
     *
     * @return the value of TRADE_VIEW.TRADETYPENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getTradetypename() {
        return tradetypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.TRADETYPENAME
     *
     * @param tradetypename the value for TRADE_VIEW.TRADETYPENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setTradetypename(String tradetypename) {
        this.tradetypename = tradetypename == null ? null : tradetypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.CARDNO
     *
     * @return the value of TRADE_VIEW.CARDNO
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.CARDNO
     *
     * @param cardno the value for TRADE_VIEW.CARDNO
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.COPENDATE
     *
     * @return the value of TRADE_VIEW.COPENDATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getCopendate() {
        return copendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.COPENDATE
     *
     * @param copendate the value for TRADE_VIEW.COPENDATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setCopendate(String copendate) {
        this.copendate = copendate == null ? null : copendate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.EXPIREDATE
     *
     * @return the value of TRADE_VIEW.EXPIREDATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getExpiredate() {
        return expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.EXPIREDATE
     *
     * @param expiredate the value for TRADE_VIEW.EXPIREDATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setExpiredate(String expiredate) {
        this.expiredate = expiredate == null ? null : expiredate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.CARDTYPE
     *
     * @return the value of TRADE_VIEW.CARDTYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.CARDTYPE
     *
     * @param cardtype the value for TRADE_VIEW.CARDTYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype == null ? null : cardtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.CARDTYPENAME
     *
     * @return the value of TRADE_VIEW.CARDTYPENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getCardtypename() {
        return cardtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.CARDTYPENAME
     *
     * @param cardtypename the value for TRADE_VIEW.CARDTYPENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setCardtypename(String cardtypename) {
        this.cardtypename = cardtypename == null ? null : cardtypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.CARDSTATUS
     *
     * @return the value of TRADE_VIEW.CARDSTATUS
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getCardstatus() {
        return cardstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.CARDSTATUS
     *
     * @param cardstatus the value for TRADE_VIEW.CARDSTATUS
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setCardstatus(String cardstatus) {
        this.cardstatus = cardstatus == null ? null : cardstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.CARDSTATUSNAME
     *
     * @return the value of TRADE_VIEW.CARDSTATUSNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getCardstatusname() {
        return cardstatusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.CARDSTATUSNAME
     *
     * @param cardstatusname the value for TRADE_VIEW.CARDSTATUSNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setCardstatusname(String cardstatusname) {
        this.cardstatusname = cardstatusname == null ? null : cardstatusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.MERCHANTID
     *
     * @return the value of TRADE_VIEW.MERCHANTID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public Integer getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.MERCHANTID
     *
     * @param merchantid the value for TRADE_VIEW.MERCHANTID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setMerchantid(Integer merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.MERCHANTNAME
     *
     * @return the value of TRADE_VIEW.MERCHANTNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getMerchantname() {
        return merchantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.MERCHANTNAME
     *
     * @param merchantname the value for TRADE_VIEW.MERCHANTNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setMerchantname(String merchantname) {
        this.merchantname = merchantname == null ? null : merchantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.MERCHANTTYPE
     *
     * @return the value of TRADE_VIEW.MERCHANTTYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getMerchanttype() {
        return merchanttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.MERCHANTTYPE
     *
     * @param merchanttype the value for TRADE_VIEW.MERCHANTTYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setMerchanttype(String merchanttype) {
        this.merchanttype = merchanttype == null ? null : merchanttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.MERCHANTTYPENAME
     *
     * @return the value of TRADE_VIEW.MERCHANTTYPENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getMerchanttypename() {
        return merchanttypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.MERCHANTTYPENAME
     *
     * @param merchanttypename the value for TRADE_VIEW.MERCHANTTYPENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setMerchanttypename(String merchanttypename) {
        this.merchanttypename = merchanttypename == null ? null : merchanttypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.ACCOUNTNO
     *
     * @return the value of TRADE_VIEW.ACCOUNTNO
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public Integer getAccountno() {
        return accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.ACCOUNTNO
     *
     * @param accountno the value for TRADE_VIEW.ACCOUNTNO
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setAccountno(Integer accountno) {
        this.accountno = accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.AOPENDATE
     *
     * @return the value of TRADE_VIEW.AOPENDATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getAopendate() {
        return aopendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.AOPENDATE
     *
     * @param aopendate the value for TRADE_VIEW.AOPENDATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setAopendate(String aopendate) {
        this.aopendate = aopendate == null ? null : aopendate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.ACCOUNTTYPE
     *
     * @return the value of TRADE_VIEW.ACCOUNTTYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getAccounttype() {
        return accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.ACCOUNTTYPE
     *
     * @param accounttype the value for TRADE_VIEW.ACCOUNTTYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setAccounttype(String accounttype) {
        this.accounttype = accounttype == null ? null : accounttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.ACCOUNTTYPENAME
     *
     * @return the value of TRADE_VIEW.ACCOUNTTYPENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getAccounttypename() {
        return accounttypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.ACCOUNTTYPENAME
     *
     * @param accounttypename the value for TRADE_VIEW.ACCOUNTTYPENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setAccounttypename(String accounttypename) {
        this.accounttypename = accounttypename == null ? null : accounttypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.ACCOUNTSTATE
     *
     * @return the value of TRADE_VIEW.ACCOUNTSTATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getAccountstate() {
        return accountstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.ACCOUNTSTATE
     *
     * @param accountstate the value for TRADE_VIEW.ACCOUNTSTATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setAccountstate(String accountstate) {
        this.accountstate = accountstate == null ? null : accountstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.ACCOUNTSTATUSNAME
     *
     * @return the value of TRADE_VIEW.ACCOUNTSTATUSNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getAccountstatusname() {
        return accountstatusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.ACCOUNTSTATUSNAME
     *
     * @param accountstatusname the value for TRADE_VIEW.ACCOUNTSTATUSNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setAccountstatusname(String accountstatusname) {
        this.accountstatusname = accountstatusname == null ? null : accountstatusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.BALANCE
     *
     * @return the value of TRADE_VIEW.BALANCE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.BALANCE
     *
     * @param balance the value for TRADE_VIEW.BALANCE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.CUSTID
     *
     * @return the value of TRADE_VIEW.CUSTID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public Integer getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.CUSTID
     *
     * @param custid the value for TRADE_VIEW.CUSTID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setCustid(Integer custid) {
        this.custid = custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.CUSTNAME
     *
     * @return the value of TRADE_VIEW.CUSTNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.CUSTNAME
     *
     * @param custname the value for TRADE_VIEW.CUSTNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.IDENTITYPE
     *
     * @return the value of TRADE_VIEW.IDENTITYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getIdentitype() {
        return identitype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.IDENTITYPE
     *
     * @param identitype the value for TRADE_VIEW.IDENTITYPE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setIdentitype(String identitype) {
        this.identitype = identitype == null ? null : identitype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.IDENTITYID
     *
     * @return the value of TRADE_VIEW.IDENTITYID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getIdentityid() {
        return identityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.IDENTITYID
     *
     * @param identityid the value for TRADE_VIEW.IDENTITYID
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setIdentityid(String identityid) {
        this.identityid = identityid == null ? null : identityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.BIRTHDAY
     *
     * @return the value of TRADE_VIEW.BIRTHDAY
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.BIRTHDAY
     *
     * @param birthday the value for TRADE_VIEW.BIRTHDAY
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.STREET
     *
     * @return the value of TRADE_VIEW.STREET
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.STREET
     *
     * @param street the value for TRADE_VIEW.STREET
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.CITY
     *
     * @return the value of TRADE_VIEW.CITY
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.CITY
     *
     * @param city the value for TRADE_VIEW.CITY
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.CITYNAME
     *
     * @return the value of TRADE_VIEW.CITYNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.CITYNAME
     *
     * @param cityname the value for TRADE_VIEW.CITYNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.STATE
     *
     * @return the value of TRADE_VIEW.STATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.STATE
     *
     * @param state the value for TRADE_VIEW.STATE
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.STATENAME
     *
     * @return the value of TRADE_VIEW.STATENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getStatename() {
        return statename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.STATENAME
     *
     * @param statename the value for TRADE_VIEW.STATENAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setStatename(String statename) {
        this.statename = statename == null ? null : statename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.GENDER
     *
     * @return the value of TRADE_VIEW.GENDER
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.GENDER
     *
     * @param gender the value for TRADE_VIEW.GENDER
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.GENDERNAME
     *
     * @return the value of TRADE_VIEW.GENDERNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getGendername() {
        return gendername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.GENDERNAME
     *
     * @param gendername the value for TRADE_VIEW.GENDERNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setGendername(String gendername) {
        this.gendername = gendername == null ? null : gendername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.EDUCATION
     *
     * @return the value of TRADE_VIEW.EDUCATION
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.EDUCATION
     *
     * @param education the value for TRADE_VIEW.EDUCATION
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADE_VIEW.EDUNAME
     *
     * @return the value of TRADE_VIEW.EDUNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public String getEduname() {
        return eduname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADE_VIEW.EDUNAME
     *
     * @param eduname the value for TRADE_VIEW.EDUNAME
     *
     * @mbggenerated Tue Nov 03 09:52:08 EST 2015
     */
    public void setEduname(String eduname) {
        this.eduname = eduname == null ? null : eduname.trim();
    }
}