package edu.bridgeport.cpsc350.project1.model;

public class Transaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADERECORD.TRADEID
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    private Integer tradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADERECORD.TADETIME
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    private String tadetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADERECORD.AMOUNT
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADERECORD.CARDID
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    private Integer cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADERECORD.MERCHANTID
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    private Integer merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRADERECORD.TRADETYPE
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    private String tradetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADERECORD.TRADEID
     *
     * @return the value of TRADERECORD.TRADEID
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    public Integer getTradeid() {
        return tradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADERECORD.TRADEID
     *
     * @param tradeid the value for TRADERECORD.TRADEID
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    public void setTradeid(Integer tradeid) {
        this.tradeid = tradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADERECORD.TADETIME
     *
     * @return the value of TRADERECORD.TADETIME
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    public String getTadetime() {
        return tadetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADERECORD.TADETIME
     *
     * @param tadetime the value for TRADERECORD.TADETIME
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    public void setTadetime(String tadetime) {
        this.tadetime = tadetime == null ? null : tadetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADERECORD.AMOUNT
     *
     * @return the value of TRADERECORD.AMOUNT
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADERECORD.AMOUNT
     *
     * @param amount the value for TRADERECORD.AMOUNT
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADERECORD.CARDID
     *
     * @return the value of TRADERECORD.CARDID
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    public Integer getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADERECORD.CARDID
     *
     * @param cardid the value for TRADERECORD.CARDID
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    public void setCardid(Integer cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADERECORD.MERCHANTID
     *
     * @return the value of TRADERECORD.MERCHANTID
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    public Integer getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADERECORD.MERCHANTID
     *
     * @param merchantid the value for TRADERECORD.MERCHANTID
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    public void setMerchantid(Integer merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRADERECORD.TRADETYPE
     *
     * @return the value of TRADERECORD.TRADETYPE
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    public String getTradetype() {
        return tradetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRADERECORD.TRADETYPE
     *
     * @param tradetype the value for TRADERECORD.TRADETYPE
     *
     * @mbggenerated Sat Oct 31 22:49:36 EDT 2015
     */
    public void setTradetype(String tradetype) {
        this.tradetype = tradetype == null ? null : tradetype.trim();
    }
}